In [1]:
import sys
print(sys.executable)

c:\Users\DELL\anaconda3\python.exe

In [2]:
import pickle
import pandas as pd
from IPython.display import display

In [3]:
chemin_pkl = r"existing_bi\boulangerie-performance--main\retail_data.pkl"

In [4]:
with open(chemin_pkl, "rb") as f:
    data = pickle.load(f)

In [5]:
print("Les tableaux disponibles sont :", list(data.keys()))

Les tableaux disponibles sont : ['df_clean', 'df_penetration', 'df_macro', 'regles', 'forecast_14j', 'forecast_saison', 'daily_data', 'ca_mensuel', 'mdape_cv']

In [8]:
df_ventes = data["df_clean"]
df_ventes.head(10)

,transaction_id,date,time,day,ticket_number,article,quantity,unit_price,total_revenue,hour,season,event,is_event,is_touristic_season,category,ticket_total_value,day_name,semaine_iso,week_id
0,1,2024-01-01,07:06:43,Lundi,295793,PAIN AU CHOCOLAT,1,1.48,1.48,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,4.30,Monday,2024-01-01/2024-01-07,2024-W01
1,2,2024-01-01,07:06:43,Lundi,295793,PAIN AU CHOCOLAT,2,1.41,2.82,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,4.30,Monday,2024-01-01/2024-01-07,2024-W01
2,3,2024-01-01,07:16:18,Lundi,295785,BAGUETTE,1,1.20,1.20,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,2.96,Monday,2024-01-01/2024-01-07,2024-W01
3,4,2024-01-01,07:16:18,Lundi,295785,PAIN AUX RAISINS,1,1.76,1.76,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,2.96,Monday,2024-01-01/2024-01-07,2024-W01
4,5,2024-01-01,08:02:12,Lundi,295779,BRIOCHETTE,2,1.11,2.22,8,Hiver,Jour de l'An,1,0,Viennoiseries,2.22,Monday,2024-01-01/2024-01-07,2024-W01
5,6,2024-01-01,08:07:54,Lundi,295791,BROWNIES,1,3.18,3.18,8,Hiver,Jour de l'An,1,0,Patisseries,3.18,Monday,2024-01-01/2024-01-07,2024-W01
6,7,2024-01-01,08:12:47,Lundi,295797,BOULE 200G,1,2.08,2.08,8,Hiver,Jour de l'An,1,0,Pains & Baguettes,2.08,Monday,2024-01-01/2024-01-07,2024-W01
7,8,2024-01-01,08:21:14,Lundi,295795,BOULE 400G,1,1.84,1.84,8,Hiver,Jour de l'An,1,0,Pains & Baguettes,6.95,Monday,2024-01-01/2024-01-07,2024-W01
8,9,2024-01-01,08:21:14,Lundi,295795,PALET BRETON,2,1.83,3.66,8,Hiver,Jour de l'An,1,0,Patisseries,6.95,Monday,2024-01-01/2024-01-07,2024-W01
9,10,2024-01-01,08:21:14,Lundi,295795,TRADITIONAL BAGUETTE,1,1.45,1.45,8,Hiver,Jour de l'An,1,0,Pains & Baguettes,6.95,Monday,2024-01-01/2024-01-07,2024-W01

In [7]:
df_ventes = data["df_penetration"]
df_ventes.head(10)

,article,tickets_count,penetration_rate_%,statut_strategique
0,TRADITIONAL BAGUETTE,57577,43.85,Produit Phare (Dominant)
1,COUPE,16035,12.21,Leader (Indispensable)
2,BAGUETTE,14573,11.10,Leader (Indispensable)
3,BANETTE,13392,10.20,Leader (Indispensable)
4,CROISSANT,10996,8.37,Leader (Indispensable)
5,PAIN AU CHOCOLAT,10258,7.81,Leader (Indispensable)
6,CEREAL BAGUETTE,4401,3.35,Produit Coeur (Core)
7,SPECIAL BREAD,4283,3.26,Produit Coeur (Core)
8,FORMULE SANDWICH,4045,3.08,Produit Coeur (Core)
9,BOULE 400G,3660,2.79,Produit Coeur (Core)

In [9]:
df_macro = data["df_macro"]
df_macro.head(10)

,article,daily_velocity,stock_securite,velocity_touristic,velocity_event,ratio_touristic,ratio_event
0,TRADITIONAL BAGUETTE,153.46,155.0,324.60,98.73,2.12,0.64
1,CROISSANT,41.11,43.0,81.56,36.67,1.98,0.89
2,PAIN AU CHOCOLAT,35.44,37.0,66.68,32.07,1.88,0.90
3,BAGUETTE,33.67,35.0,51.20,38.65,1.52,1.15
4,BANETTE,31.17,32.0,59.46,27.24,1.91,0.87
5,COUPE,29.24,30.0,57.85,17.70,1.98,0.61
6,CEREAL BAGUETTE,10.27,11.0,17.74,6.33,1.73,0.62
7,FORMULE SANDWICH,8.11,9.0,9.73,4.31,1.20,0.53
8,TARTELETTE,7.21,8.0,10.30,5.58,1.43,0.77
9,SPECIAL BREAD,6.89,7.0,12.77,4.45,1.85,0.65

In [11]:
df_regles = data["regles"]
df_regles.head(3)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedents_str,consequents_str
0,(VIK BREAD),"(TRADITIONAL BAGUETTE, COUPE)",0.039492,0.082783,0.014605,0.369815,4.467283,1.0,0.011335,1.455472,0.808062,0.135643,0.312938,0.273118,VIK BREAD,"COUPE, TRADITIONAL BAGUETTE"
1,"(TRADITIONAL BAGUETTE, COUPE)",(VIK BREAD),0.082783,0.039492,0.014605,0.176421,4.467283,1.0,0.011335,1.166261,0.846201,0.135643,0.142559,0.273118,"COUPE, TRADITIONAL BAGUETTE",VIK BREAD
2,(COUPE),(BOULE 200G),0.272835,0.041043,0.033497,0.122772,2.991317,1.0,0.022299,1.093168,0.915472,0.119468,0.085227,0.469454,COUPE,BOULE 200G

In [12]:
df_f14 = data["forecast_14j"]
df_f14.head(10)

,ds,yhat,yhat_lower,yhat_upper,jour_semaine,date_fr,horizon,is_ferme
620,2026-01-01,393,95,706,Jeudi,01/01/2026,J+1,0
621,2026-01-02,527,248,852,Vendredi,02/01/2026,J+2,0
622,2026-01-03,444,140,741,Samedi,03/01/2026,J+3,0
623,2026-01-04,437,129,723,Dimanche,04/01/2026,J+4,0
624,2026-01-05,453,144,742,Lundi,05/01/2026,J+5,0
625,2026-01-06,474,174,781,Mardi,06/01/2026,J+6,0
626,2026-01-07,0,0,0,Mercredi,07/01/2026,J+7,1
627,2026-01-08,749,442,1060,Jeudi,08/01/2026,J+8,0
628,2026-01-09,500,203,791,Vendredi,09/01/2026,J+9,0
629,2026-01-10,478,190,766,Samedi,10/01/2026,J+10,0

In [13]:
df_fsaison = data["forecast_saison"]
df_fsaison.head(10)

,ds,yhat,yhat_lower,yhat_upper,mois_num,facteur,jour_semaine,date_fr,is_ferme,mois
771,2026-06-01,658,190,1131,6,1.5,Lundi,01/06/2026,0,June 2026
772,2026-06-02,660,171,1089,6,1.5,Mardi,02/06/2026,0,June 2026
773,2026-06-03,497,56,936,6,1.5,Mercredi,03/06/2026,0,June 2026
774,2026-06-04,958,533,1441,6,1.5,Jeudi,04/06/2026,0,June 2026
775,2026-06-05,620,190,1062,6,1.5,Vendredi,05/06/2026,0,June 2026
776,2026-06-06,569,72,1034,6,1.5,Samedi,06/06/2026,0,June 2026
777,2026-06-07,526,67,990,6,1.5,Dimanche,07/06/2026,0,June 2026
778,2026-06-08,515,63,980,6,1.5,Lundi,08/06/2026,0,June 2026
779,2026-06-09,512,61,914,6,1.5,Mardi,09/06/2026,0,June 2026
780,2026-06-10,346,0,805,6,1.5,Mercredi,10/06/2026,0,June 2026

In [14]:
df_ca_mois = data["ca_mensuel"]
df_ca_mois.head(10)

        date  total_revenue
0 2024-01-01       35503.72
1 2024-02-01       17404.62
2 2024-03-01       26187.69
3 2024-04-01       25716.96
4 2024-05-01       42457.45
5 2024-06-01       25790.88
6 2024-07-01       48977.60
7 2024-08-01       57652.97
8 2024-09-01       23704.48
9 2024-10-01       22651.28

In [15]:
erreur = data["mdape_cv"]
print("Erreur MDAPE :", erreur, "%")

Erreur MDAPE : 20.927606327860847 %

In [20]:


df_all = data["df_clean"].copy()
df_all["date"] = pd.to_datetime(df_all["date"], errors="coerce")
df_all = df_all.dropna(subset=["date"]).copy()
df_all["day"] = df_all["date"].dt.date
for col in ["quantity","total_revenue","hour"]:
    if col not in df_all.columns: df_all[col] = 0.0
    df_all[col] = pd.to_numeric(df_all[col], errors="coerce").fillna(0)
df_all["hour"] = df_all["hour"].astype(int).clip(0,23)
if "article"  not in df_all.columns: df_all["article"]  = "Produit"
if "category" not in df_all.columns: df_all["category"] = "Autre"
if "ticket_number" not in df_all.columns: df_all["ticket_number"] = df_all.index.astype(str)
df_all["article"]  = df_all["article"].fillna("Produit").astype(str)
df_all["category"] = df_all["category"].fillna("Autre").astype(str)

available_days = sorted(df_all["day"].dropna().unique())
selected_day = available_days[-1]

sel_ts  = pd.Timestamp(selected_day)
day_df  = df_all[df_all["day"] == sel_ts.date()].copy()
dow     = sel_ts.weekday()
JOURS_FR_LONG = ["Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi","Dimanche"]
jour_str = JOURS_FR_LONG[dow]

print(sel_ts)

2025-12-31 00:00:00

In [21]:
day_df

,transaction_id,date,time,day,ticket_number,article,quantity,unit_price,total_revenue,hour,season,event,is_event,is_touristic_season,category,ticket_total_value,day_name,semaine_iso,week_id
231551,231552,2025-12-31,07:09:07,2025-12-31,304791,BRIOCHE DE NOEL,1,7.29,7.29,7,Hiver,Reveillon,1,0,Viennoiseries,30.02,Wednesday,2025-12-29/2026-01-04,2026-W01
231552,231553,2025-12-31,07:09:07,2025-12-31,304791,ROYAL 6P,1,22.73,22.73,7,Hiver,Reveillon,1,0,Patisseries,30.02,Wednesday,2025-12-29/2026-01-04,2026-W01
231553,231554,2025-12-31,07:19:44,2025-12-31,305077,BUCHE 6PERS,1,26.02,26.02,7,Hiver,Reveillon,1,0,Produits Festifs,107.92,Wednesday,2025-12-29/2026-01-04,2026-W01
231554,231555,2025-12-31,07:19:44,2025-12-31,305077,GD PLATEAU SALE,1,22.46,22.46,7,Hiver,Reveillon,1,0,Traiteur & Sale,107.92,Wednesday,2025-12-29/2026-01-04,2026-W01
231555,231556,2025-12-31,07:19:44,2025-12-31,305077,BUCHE 6PERS,1,24.78,24.78,7,Hiver,Reveillon,1,0,Produits Festifs,107.92,Wednesday,2025-12-29/2026-01-04,2026-W01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232543,232544,2025-12-31,17:55:53,2025-12-31,295758,BUCHE 6PERS,1,26.07,26.07,17,Hiver,Reveillon,1,0,Produits Festifs,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232544,232545,2025-12-31,17:55:53,2025-12-31,295758,PALET BRETON,1,1.75,1.75,17,Hiver,Reveillon,1,0,Patisseries,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232545,232546,2025-12-31,17:55:53,2025-12-31,295758,GD FAR BRETON,2,9.09,18.18,17,Hiver,Reveillon,1,0,Produits Festifs,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232546,232547,2025-12-31,17:55:53,2025-12-31,295758,GUERANDAIS,1,4.60,4.60,17,Hiver,Reveillon,1,0,Pains & Baguettes,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232547,232548,2025-12-31,18:12:47,2025-12-31,295760,BUCHE 6PERS,1,25.79,25.79,18,Hiver,Reveillon,1,0,Produits Festifs,25.79,Wednesday,2025-12-29/2026-01-04,2026-W01

In [22]:
df_all

,transaction_id,date,time,day,ticket_number,article,quantity,unit_price,total_revenue,hour,season,event,is_event,is_touristic_season,category,ticket_total_value,day_name,semaine_iso,week_id
0,1,2024-01-01,07:06:43,2024-01-01,295793,PAIN AU CHOCOLAT,1,1.48,1.48,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,4.30,Monday,2024-01-01/2024-01-07,2024-W01
1,2,2024-01-01,07:06:43,2024-01-01,295793,PAIN AU CHOCOLAT,2,1.41,2.82,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,4.30,Monday,2024-01-01/2024-01-07,2024-W01
2,3,2024-01-01,07:16:18,2024-01-01,295785,BAGUETTE,1,1.20,1.20,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,2.96,Monday,2024-01-01/2024-01-07,2024-W01
3,4,2024-01-01,07:16:18,2024-01-01,295785,PAIN AUX RAISINS,1,1.76,1.76,7,Hiver,Jour de l'An,1,0,Pains & Baguettes,2.96,Monday,2024-01-01/2024-01-07,2024-W01
4,5,2024-01-01,08:02:12,2024-01-01,295779,BRIOCHETTE,2,1.11,2.22,8,Hiver,Jour de l'An,1,0,Viennoiseries,2.22,Monday,2024-01-01/2024-01-07,2024-W01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232543,232544,2025-12-31,17:55:53,2025-12-31,295758,BUCHE 6PERS,1,26.07,26.07,17,Hiver,Reveillon,1,0,Produits Festifs,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232544,232545,2025-12-31,17:55:53,2025-12-31,295758,PALET BRETON,1,1.75,1.75,17,Hiver,Reveillon,1,0,Patisseries,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232545,232546,2025-12-31,17:55:53,2025-12-31,295758,GD FAR BRETON,2,9.09,18.18,17,Hiver,Reveillon,1,0,Produits Festifs,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232546,232547,2025-12-31,17:55:53,2025-12-31,295758,GUERANDAIS,1,4.60,4.60,17,Hiver,Reveillon,1,0,Pains & Baguettes,50.60,Wednesday,2025-12-29/2026-01-04,2026-W01
232547,232548,2025-12-31,18:12:47,2025-12-31,295760,BUCHE 6PERS,1,25.79,25.79,18,Hiver,Reveillon,1,0,Produits Festifs,25.79,Wednesday,2025-12-29/2026-01-04,2026-W01